services:
  instance:
    image: ghcr.io/torikushiii/endfield-auto:latest
    restart: on-failure:5
    container_name: endfield-auto
    network_mode: bridge
    volumes:
      - ./config.json:/app/config.json
    environment:
      - TZ=Asia/Shanghai
